src/flats/urls.py
from django.conf.urls import patterns, url

from flats import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
	# ex: /flat/5/
    url(r'^(?P<flat_id>\d+)/$', views.detail, name='detail'),
	url(r'^(?P<flat_id>\d+)/gallery/$', views.bigmonitor, name='gallery'),
	url(r'^(?P<flat_id>\d+)/panorama/(?P<interior_id>\d+)/$', views.panorama, name='panorama'),
)

src/where2stay/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),

                       # Examples:
                       url(r'^$', 'where2stay.views.home', name='home'),
                       # url(r'^where2stay/', include('where2stay.foo.urls')),
                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^apartments/', include('flats.urls', namespace='flats')),
                       url(r'^contact/$', 'where2stay.views.contact', name="contact"),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT
                            })
    )

src/flats/models.py
# coding=utf-8
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField
from easy_thumbnails.files import get_thumbnailer
from geopy import geocoders
from django.conf import settings

geo = geocoders.GoogleV3()


class Flat(models.Model):
    name = models.CharField(max_length=200, default='flat_name')
    overview = models.TextField(blank=True)
    published = models.BooleanField(default=False)
    isFree = models.BooleanField("it is boobked", default=True)
    price = models.IntegerField(max_length=5, blank=True, default=150)
    address = models.CharField(max_length=200)
    geo_lat = models.FloatField(default=settings.EASY_MAPS_CENTER[0])
    geo_lng = models.FloatField(default=settings.EASY_MAPS_CENTER[1])

    def __unicode__(self):
        return self.name

    def roomNumber(self):
        return Interior.objects.filter(flat=self.id).count()

    def save(self, *args, **kwargs):
        place, (lat, lng) = geo.geocode(self.address)
        self.geo_lat = lat
        self.geo_lng = lng
        super(Flat, self).save(*args, **kwargs)


def upload_path(self, filename):
    split = filename.rsplit('.', 1)
    extension = split[1]
    if self.id is None:
        inter = self.name
    else:
        inter = self.id
    return 'admin/flat' + str(self.flat.id) + '/interior' + str(inter) + '.' + extension

# return 'admin/flat' + str(self.flat.id) + '/interior-' + str(self.name) + '.' + extension


class Interior(models.Model):
    flat = models.ForeignKey(Flat, null=True)
    name = models.CharField(max_length=200, default='room')
    description = models.TextField(blank=True)
    panorama = models.BooleanField(default=False)
    photo = ThumbnailerImageField(default="", upload_to=upload_path, blank=True)
    thumb_url = models.CharField(max_length=500, default='link/to/thumbnail/')

    def __unicode__(self):
        return self.name

    def image_thumb(self):
        return '<img src="%s" />' % get_thumbnailer(self.photo)['flat_small'].url

    image_thumb.short_description = 'Thumb'
    image_thumb.allow_tags = True

    def save(self, *args, **kwargs):
        self.thumb_url = get_thumbnailer(self.photo)['flat_small'].url
        super(Interior, self).save(*args, **kwargs)

src/where2stay/forms.py
from django import forms

class ContactForm(forms.Form):
    sender = forms.EmailField(label='Your email')
    subject = forms.CharField(max_length=100, label='Subject')
    message = forms.CharField(label='message')

src/flats/views.py
from django.http import Http404
from django.template import Context
from django.shortcuts import render, get_object_or_404, get_list_or_404
from flats.models import Flat, Interior


def index(request):
    flat_list = Flat.objects.all()
    context = Context({
        'flat_list': flat_list,
    })
    return render(request, 'flats/flats.html', context)


def detail(request, flat_id):
    # return HttpResponse("You're looking at flat %s." % flat_id)
    flat = get_object_or_404(Flat, pk=flat_id)
    interior = get_list_or_404(Interior, flat=flat_id)
    return render(request, 'flats/detail.html', {'flat': flat, 'interior': interior})


def bigmonitor(request, flat_id):
    flat = get_object_or_404(Flat, pk=flat_id)
    interior = get_list_or_404(Interior, flat=flat_id)
    return render(request, 'flats/gallery.html', {'flat': flat, 'interior': interior})


def panorama(request, flat_id, interior_id):
    flat = get_object_or_404(Flat, pk=flat_id)
    interior = get_list_or_404(Interior, flat=flat_id, id=interior_id)
    int = interior[0]
    if not int.panorama:
        raise Http404
    return render(request, 'flats/panorama.html', {'flat': flat, 'interior': interior[0]})

src/where2stay/views.py
from django.template import Context
from django.shortcuts import render, get_object_or_404

from forms import *


def home(request):
	context = Context({})
	return render(request, 'home.html', context)


def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			sender = form.cleaned_data['sender']
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			message += "\nrequest from sender is %s" % sender
			from django.core.mail import mail_managers
			mail_managers(subject, message, fail_silently=False, connection=None, html_message=None)
	else:
		form = ContactForm()

	# context = Context()
	return render(request, "contact.html", {'form': form, })

src/templates/base.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stati-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>

	<meta charset="utf-8" />
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width" />

	<title>Where2stay</title>

	{% block css %}
		<!-- Included CSS Files (Compressed) -->
		<link rel="stylesheet" href="{{STATIC_URL}}css/foundation.min.css">
		<link rel="stylesheet" href="{{STATIC_URL}}css/main.css">
		<link rel="stylesheet" href="{{STATIC_URL}}css/app.css">
		<script src="{{STATIC_URL}}js/modernizr.foundation.js"></script>
		<link rel="stylesheet" href="{{STATIC_URL}}css/ligature.css">
	{% endblock %}

	<!-- Google fonts -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />

	<!-- IE Fix for HTML5 Tags -->
	<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

</head>

<body>
<!-- ######################## Main Menu ######################## -->

{% block menu %}
	{% load flat_tag %}
	<nav>
		<div class="twelve columns header_nav">
			<div class="row">
				<ul id="menu-header" class="nav-bar horizontal">
					<li class=""><a href="{% url 'home' %}">Home</a></li>
					{% show_flat_list %}
					<li class=""><a href="{% url 'contact' %}">Contacts</a></li>
				</ul>
				<script type="text/javascript">
				//<![CDATA[
				$('ul#menu-header').nav-bar();
				//]]>
				</script>
			</div>
		</div>
	</nav>
{% endblock %}

{% block content %}
{% endblock %}

<!-- ######################## Footer ######################## -->
<footer>

      <div class="row">
      
          <div class="twelve columns footer">
              <a href="http://twitter.com/dieterarno" class="lsf-icon" style="font-size:16px; margin-right:15px" title="twitter">Twitter</a> 
              <a href="https://www.facebook.com/sergei.wilson" class="lsf-icon" style="font-size:16px; margin-right:15px" title="facebook">Facebook</a>
              <a href="https://www.airbnb.ru/users/show/6322184" class="lsf-icon" style="font-size:16px; margin-right:15px" title="global">Airbnb</a>
              <a href="http://about.me/mcgr0g/" class="lsf-icon" style="font-size:16px" title="power">Powered by mcgr0g</a>
          </div>
          
      </div>

</footer>		  

<!-- ######################## Scripts ######################## -->

{% block scripts %}
	<script src="{{STATIC_URL}}js/foundation.min.js" type="text/javascript"></script>
	<script src="{{STATIC_URL}}js/app.js" type="text/javascript"></script>
{% endblock %}

</body>
</html>

src/templates/contact.html
{% extends "base.html" %}

{% block content %}
<!-- ######################## Header ######################## -->
        
<header>
	<h1 class="welcome_text">Contact Page</h1>
</header>
   
<!-- ######################## Section ######################## -->
      
<section class="section_light">
	<div class="row">
        <div class="six columns">
{#			<h3>Address</h3>#}
{#			<p><strong>Business INC</strong></p>#}
{#			<p>Telephone: 99 88 77 66<br />#}
{#			E-mail: mail@doe.com</p><!-- // MAILCHIMP SUBSCRIBE CODE \\ -->#}
{#			<p><a href="#">Subscribe to Newsletter</a></p>#}
{#			<!-- \\ MAILCHIMP SUBSCRIBE LINK // -->#}
{#			<p><strong>Office: mon-fri 10.00 - 16.30</strong><br />#}
{#			<em>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum porttitor lacus.</em></p>#}
{#			<!-- Contact Form -->#}
{#			<h3>Contact Form</h3>#}
{#			<!-- Row Layout for forms -->#}
			<form action="{% url 'contact' %}" method="post">{% csrf_token %}
				<label>{{ form.sender.label }}</label>
{#				<input class="error"/>#}
				<input type="text" name="sender"
					{% if not form.sender.errors %}
						placeholder="example@mail.com"  />
					{% else %}
						class="error" placeholder="{{ form.sender.errors.as_text }}"/>
					{% endif %}
				<label>{{ form.subject.label }}</label>
				<input name="subject" type="text" class="twelve" placeholder="interested in flat 1234" />
				<textarea name="message" placeholder="Message"></textarea>
				<input type="submit" value="Send message" class="button success" />
			</form>
        </div>
		<div class="six columns">
				{% load easy_maps_tags %}
				{% easy_map "Russia, Ekaterinburg, Mira 32" 100% 400 %}
{#			<h3>Where to find us</h3>#}
{#				<iframe src=#}
{#				"http://maps.google.no/maps?f=q&amp;source=s_q&amp;hl=no&amp;geocode=&amp;q=Dieter+Schneider,+Hafstadvegen+34,+F%C3%B8rde&amp;aq=0&amp;oq=hafstadvegen+34+&amp;sll=61.450282,5.85535&amp;sspn=0.008368,0.027874&amp;g=hafstadvegen+34&amp;ie=UTF8&amp;hq=Dieter+Schneider,&amp;hnear=Hafstadvegen+34,+6800+F%C3%B8rde,+Sogn+og+Fjordane&amp;t=m&amp;ll=61.453106,5.857172&amp;spn=0.009536,0.019913&amp;z=15&amp;iwloc=A&amp;output=embed"#}
{#				style="width:400px; height:375px; border:0">#}
{#				</iframe><br />#}
{#			<small>#}
{#				<a style="color: #0000ff; text-align: left;" href=#}
{#				"http://maps.google.no/maps?f=q&amp;source=embed&amp;hl=no&amp;geocode=&amp;q=Dieter+Schneider,+Hafstadvegen+34,+F%C3%B8rde&amp;aq=0&amp;oq=hafstadvegen+34+&amp;sll=61.450282,5.85535&amp;sspn=0.008368,0.027874&amp;g=hafstadvegen+34&amp;ie=UTF8&amp;hq=Dieter+Schneider,&amp;hnear=Hafstadvegen+34,+6800+F%C3%B8rde,+Sogn+og+Fjordane&amp;t=m&amp;ll=61.453106,5.857172&amp;spn=0.009536,0.019913&amp;z=15&amp;iwloc=A">#}
{#				Enlarge map</a>#}
{#			</small>#}
		</div>
	</div>
</section>
        
{% endblock %}

src/templates/flats/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load easy_maps_tags %}

{% block css %}
	{{ block.super }}
	<!-- Magnific Popup core CSS file -->
	<link rel="stylesheet" href="{{STATIC_URL}}css/magnific-popup.css">
	<!-- Magnific Popup developer init CSS file -->
	<link rel="stylesheet" href="{{STATIC_URL}}css/magnific-popup.init.css">
{% endblock %}

{% block content %}
<!-- ######################## Header ######################## -->
<header>
	<div class="row">
		<article>
			<div class="twelve columns">
				<h1>{{ flat.name }}</h1>
				<p class="excerpt">{{ flat.overview }}</p>
			 </div>
		</article>
	</div>
</header>
<!-- ######################## Section ######################## -->

<section>
	<div class="section_main">
		<div class="row">
			<section class="eight columns">

				{% for int in interior %}
					<article class="blog_post">
						<div class="gallery-container">
							<div class="three columns">
								{% if not int.panorama %}
									<a class="th lightbox" href="{{ MEDIA_URL }}{{ int.photo }}" title="{{ int.name }}">
								{% else %}
									<a class="th" href="{% url 'flats:panorama' flat.id int.id %}">
								{% endif %}
									<img src="{{ int.thumb_url }}" alt="{{ int.name }}"></a>
							</div>

							<div class="nine columns">
									<h3>{{ int.name }}</h3>
									<p>{{ int.description }}</p>
							</div>
						</div>
					</article>
				{% endfor %}

			</section>

			<section class="four columns">
{#					<h2>Sidebar</h2>#}
				<div class="panel">
{#					<h3>Price</h3>#}
					<p><strong>Price:</strong> {{ flat.price }} $</p>
					<p><strong>Status:</strong>
						{% if flat.isFree %}
							Free
						{% else %}
							Boocked
						{% endif %}
					</p>
					<h3>SubMenu</h3>
					<ul class="accordion">

						<li class="active">
							<div class="title">
								<span class="dropcap_grey lsf-icon-accordion" title="geo"></span>
								<h5>Where it is?</h5>
							</div>
							<div class="content">
								<p>Google maps says
									<a class="gmap" href="https://maps.google.com/maps?q={{ flat.geo_lat }},{{ flat.geo_lng }}&hl=en" >here</a>
								</p>
							</div>
						</li>

						<li>
							<div class="title">
								<span class="dropcap_grey lsf-icon-accordion" title="shopping"></span>
								<h5>I want it!</h5>
							</div>
							<div class="content">
								<p>Contact me</p>
							</div>
						</li>

						<li>
							<div class="title">
								<span class="dropcap_grey lsf-icon-accordion" title="pc"></span>
								<h5>For big monitors</h5>
							</div>
							<div class="content">
								<p>
									<a href="{% url 'flats:gallery' flat.id %}">Page variant</a> with big traffic for desktops</p>
							</div>
						</li>

						<li>
							<div class="title">
								<span class="dropcap_grey lsf-icon-accordion" title="tile"></span>
								<h5>Find out more</h5>
							</div>
							<div class="content">
								<p>Choose suitable appartment in <a href="{% url 'flats:index' %}">price table</a> </p>
							</div>
						</li>

					</ul>

				</div>
			</section>

		</div>
	</div>
</section>
{% endblock %}

{% block scripts %}
	{{ block.super }}
	<!-- jQuery 1.7.2+ or Zepto.js 1.0+ -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<!-- Magnific Popup core JS file -->
	<script src="{{STATIC_URL}}js/jquery.magnific-popup.js"></script>
	<!-- Magnific Popup developer initiation -->
	<script src="{{STATIC_URL}}js/jquery.magnific-popup.init.js"></script>
{% endblock %}

src/templates/flats/flat_list.html
<li class="has-flyout">
<a href="#">Apartments</a><a href="#" class="flyout-toggle"></a>
<ul class="flyout"><!-- Flyout Menu -->
	{% for flat in flats %}
		{% if flat.published %}
			<li class="has-flyout"><a href={% url 'flats:detail' flat.id %}>{{ flat.name }}</a></li>
		{% endif %}
	{% endfor %}
</ul>
</li><!-- END Flyout Menu -->

src/templates/flats/flats.html
{% extends "base.html" %}
{% load flat_tag %}

{% block content %}
<!-- ######################## Header ######################## -->

<header>
	  <h1 class="heading_supersize">Apartments</h1>
</header>

<!-- ######################## Section ######################## -->
<section class="section_light">
	<div class="row" style="padding-top: 20px">
		{% if flat_list %}
			{% for flat in flat_list %}
				<div class="four columns">
					<ul class="pricing-table">
						<li class="title">{{ flat.name }}</li>
						<li class="price">Price per day:{{ flat.price }}$</li>
						<li class="description">{{ flat.overview }}</li>
						<li class="bullet-item">Status:
							{% if flat.status %}Ready for you!
							{% else %}Boocked.
							{% endif %}
						</li>
						<li class="bullet-item">Rooms: {{ flat.roomNumber }}</li>
						<li class="cta-button"><a class="button" href="{% url 'flats:detail' flat.id %}">View tour &raquo;</a></li>
					</ul>
				</div>
			{% endfor %}
		{% else %}
			<p>No flats are available.</p>
		{% endif %}
	</div>
</section>

{% endblock %}

src/templates/flats/gallery.html
{% extends "base.html" %}

{% block css %}
{{ block.super }}
	<link rel="stylesheet" href="{{STATIC_URL}}css/panorama360.css"/>
{% endblock %}

{% block content %}
<!-- ######################## Header ######################## -->
<header>
	<div class="row">
		<article>
			<div class="twelve columns">
				<h1>{{ flat.name }}</h1>
				<p class="excerpt">{{ flat.overview }}</p>
			</div>
		</article>
	</div>
</header>

{% for int in interior %}
<!-- ######################## Section ######################## -->
	{% if not int.panorama %}
		<section class="section_light">
			<div class="row">
				<h2 style="text-align:center">{{ int.name }}</h2>
				<img src="{{ MEDIA_URL }}{{ int.photo }}"/>
			</div>
		</section>
	{% else %}
		<section class="section_dark">
			<div class="row">
				<h2 style="text-align:center">{{ int.name }}</h2>
				<div class="panorama" style="height:500px;">
					<div class="panorama-view">
						<div class="panorama-container">
							<img src="{{ MEDIA_URL }}{{ int.photo }}" data-height="500" data-width="{{ int.photo.width }}" alt="panorama"/>
						</div>
					</div>
				</div>
{#				<img src="{{ MEDIA_URL }}{{ int.photo }}"/>#}
			</div>
		</section>
	{% endif %}
{% endfor %}

{% endblock%}

{% block scripts %}
	{{ block.super }}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script src="{{STATIC_URL}}js/jquery.mousewheel.min.js"></script>
	<script src="{{STATIC_URL}}js/jquery.panorama360.js"></script>
	<script>
	<!--
		$(function(){
			$('.panorama-view').panorama360();
		});
	-->
	</script>
{% endblock %}

src/templates/flats/panorama.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>Panorama 360&deg;</title>
	<meta name="description" content="panorama vieiw" />
	<link rel="stylesheet" href="{{STATIC_URL}}css/panorama360.css" media="all" />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
	<script src="{{STATIC_URL}}js/jquery.mousewheel.min.js"></script>
	<script src="{{STATIC_URL}}js/jquery.panorama360.js"></script>
	<script>
	<!--
		$(function(){
			$('.panorama-view').panorama360();
		});
	-->
	</script>
</head>
<body>
	<div class="panorama">
		<div class="panorama-view">
			<div class="panorama-container">
				<img src="{{ MEDIA_URL }}{{ interior.photo }}" data-height="{{ interior.photo.height }}" data-width="{{ interior.photo.width }}" data-width="{{ interior.photo.width }}" alt="panorama"/>
			</div>
			<a class="info round" href="{{ SITE }}{% url 'flats:detail' flat_id=flat.id %}">Go back</a>
		</div>
	</div>
</body>
</html>

src/templates/home.html
{% extends "base.html" %}


{% block css %}
	{{ block.super }}
	<!-- Magnific Popup core CSS file -->
	<link rel="stylesheet" href="{{STATIC_URL}}css/magnific-popup.css">
	<!-- Magnific Popup developer init CSS file -->
	<link rel="stylesheet" href="{{STATIC_URL}}css/magnific-popup.init.css">
{% endblock %}

{% block content %}
<!-- ######################## Header ######################## -->
        
	<header>
		  <h2 class="heading_supersize">WHERE 2 STAY</h1>
		  <h3 class="welcome_text">Looking where to stay at Praha on holidays? Welcome to our tour!</h3>
	</header>

<!-- ######################## Section ######################## -->
     
   <section class="section_light">
   
		<div class="row">

			<div class="four columns">
				<h3><span class="dropcap_red lsf-icon-dropcap" title="camera"></span> Photos of iterior</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc viverra, lacus id interdum ultrices, elit metus semper tellus, vel lacinia libero purus vitae risus.</p>
			</div>

        	<div class="four columns">
				<h3><span class="dropcap_red lsf-icon-dropcap" title="image"></span> Panorama of interior</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc viverra, lacus id interdum ultrices, elit metus semper tellus, vel lacinia libero purus vitae risus.</p>
			</div>

			<div class="four columns">
				<h3><span class="dropcap_red lsf-icon-dropcap" title="map"></span> Location on Google map</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc viverra, lacus id interdum ultrices, elit metus semper tellus, vel lacinia libero purus vitae risus.</p>
			</div>
        </div>
        
    </section>

<!-- ######################## Section ######################## -->

   <section  class="section_dark">
   
      <div class="row"> 
      
      <h2>Latest Photos by Our Members</h2>
      
          <div class="two columns">
			  <a class="th lightbox" href="{{STATIC_URL}}img/fun/tits1.jpg" title="Эмоции">
				  <img src="{{STATIC_URL}}img/fun/pre1.jpg" alt="Эмоции"></a>
			  </a>
          </div>

		  <div class="two columns">
          	<a class="th lightbox" href="{{STATIC_URL}}img/fun/tits2.jpg" title="Присмотрись">
				  <img src="{{STATIC_URL}}img/fun/pre2.jpg" alt="Присмотрись"></a>
          </div>

          <div class="two columns">
          	<a class="th lightbox" href="{{STATIC_URL}}img/fun/tits3.jpg" title="Климат">
				  <img src="{{STATIC_URL}}img/fun/pre3.jpg" alt="Климат"></a>
          </div>
          
          <div class="two columns">
          	<a class="th lightbox" href="{{STATIC_URL}}img/fun/tits4.jpg" title="Не отвертеться">
				  <img src="{{STATIC_URL}}img/fun/pre4.jpg" alt="Не отвертеться"></a>
          </div>
          
          <div class="two columns">
          	<a class="th lightbox" href="{{STATIC_URL}}img/fun/tits5.jpg" title="Разработка">
				  <img src="{{STATIC_URL}}img/fun/pre5.jpg" alt="Разработка"></a>
          </div>
          
          <div class="two columns">
          	<a class="th lightbox" href="{{STATIC_URL}}img/fun/tits6.jpg" title="Милаха">
				  <img src="{{STATIC_URL}}img/fun/pre6.jpg" alt="Милаха"></a>
          </div>

      
      </div>
      
    </section>
      
<!-- ######################## Section ######################## -->

<section class="section_main">

      <h2 style="text-align:center">Discover Hidden Treasures</h2>
      
      <div class="row">
      
          <article class="six columns">
                <div class="panel">
                    <h3>Lorem Ipsum</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec cursus fermentum metus, id commodo sapien. Donec cursus fermentum metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec cursus fermentum metus, id commodo sapien. Donec cursus fermentum metus.</p>
                  <a href="#" class="button secondary small radius">Learn More &raquo;</a>
                </div>
          </article>
          
              
          <article class="six columns">
                <div class="panel">
                    <h3>Lorem Ipsum</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec cursus fermentum metus, id commodo sapien. Donec cursus fermentum metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec cursus fermentum metus, id commodo sapien. Donec cursus fermentum metus.</p>
                  <a href="#" class="button secondary small radius">Learn More &raquo;</a>
                </div>
          </article>
  
      </div>
      
      
</section>
{% endblock %}

{% block scripts %}
	{{ block.super }}
	<!-- jQuery 1.7.2+ or Zepto.js 1.0+ -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<!-- Magnific Popup core JS file -->
	<script src="{{STATIC_URL}}js/jquery.magnific-popup.js"></script>
	<!-- Magnific Popup developer initiation -->
	<script src="{{STATIC_URL}}js/jquery.magnific-popup.init.js"></script>
{% endblock %}